### PR TITLE
Disable Flavor access change and update in horizon

### PR DESCRIPTION
**Pull request by TieWei**
Because update flavor will create a new one with different flavor
id which will remove accss for private flavors. And tiny flavor access
will change a public flavor to private one, so disable them in horizon
could avoid it happen.

Change-Id: Ic135c4e404844632279bf7b59f9ff1a075ca64d6
Closes-rally-bug: DE544

### CODE REVIEW

**Comment by mattpopow** [comment]
+1 :ok_hand: :100:

**Comment by michaeltchapman** [comment]
+1

**Comment by retr0h** [comment]
This looks very similar to #17.  Why not have #17 corrected with what we want vs submitting a brand new PR.

**Comment by TieWei** [comment]
NVM, we can also wait for #17 update to merge and close this one

**Comment by retr0h** [comment]
Lets not stop on #17.

**Pull request closed without merging**
